# Generated by Django 6.0.4 on 2026-07-21 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='link',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
